const data = [
    {
        id: 1,
        imagePath: "images/img_maldives.jpg",
        description : "Maison sur pilotis aux Maldives",
        done: false,
        link : "https://maldives-a-la-carte.com/bungalow-pilotis",
        coordinates : { lat: 2.8589496190923653, lng: 73.53871138111336 },
        alt : "Image Maldives",
    },
    {
        id: 2,
        imagePath: "images/img_kenya.jpg",
        description : "Faire un safari au Kenya",
        done: false,
        link : "https://safarienafrique.fr/safari-kenya-et-ouganda-en-decembre-et-janvier/?cq_src=bing_ads&cq_cmp=Ouganda&cq_con=DSA%20-%20Ouganda&cq_term=ouganda&cq_med=&cq_net=o&cq_plt=bp&msclkid=3fb51bb865b91873b23c7358b1338cb3&utm_source=bing&utm_medium=cpc&utm_campaign=Ouganda&utm_term=ouganda&utm_content=DSA%20-%20Ouganda",
        coordinates : { lat: -0.52483, lng: 36.664008 },
        alt : "Image Kenya",
    },
    {
        id: 3,
        imagePath: "images/img_orient-express.jpg",
        description : "Voyager à bord de l'Orient Express de Paris à Istanbul",
        done: false,
        link : "https://www.discoverytrains.net/train-de-luxe/europe/turquie/orient-express-vs-paris-budapest-istanbul",
        coordinates : { lat: 41.015307, lng: 28.976856 },
        alt : "Image Orient Express",
    },
    {
        id: 4,
        imagePath: "images/img_pandas.jpg",
        description : "Visiter la base des pandas de Chengdu",
        done: false,
        link : "https://www.chinajourneyguide.com/fr/chengdu-panda-base/",
        coordinates : { lat: 30.733234431306663, lng: 104.14462182826738 },
        alt : "Image Pandas",
    },
    {
        id: 5,
        imagePath: "images/img_nba.jpg",
        description : "Voir un match de NBA à San Antonio",
        done: false,
        link : "https://www.groupecouleur.com/tous-sports/basket-us/les-franchises/san-antonio-spurs-billet.html",
        coordinates : { lat: 29.4269444, lng: -98.4375 },
        alt : "Image salle SPURS",
    },
    {
        id: 6,
        imagePath: "images/img_laponie.jpg",
        description : "Voyager en Laponie pour le Nouvel An",
        done: false,
        link : "https://www.comptoirdesvoyages.fr/voyage/finlande/voyage-nouvel-an-levi-laponie/194",
        coordinates : { lat: 69.0231591192566, lng: 21.425585210666462 },
        alt : "Image Laponie",
    },
    {
        id: 7,
        imagePath: "images/img_taj_mahal.jpg",
        description : "Visiter le Taj Mahal en Inde",
        done: false,
        link : "https://www.voyageursdumonde.fr/voyage-sur-mesure/recherche-voyage-tag/voyage-taj-mahal",
        coordinates : { lat: 27.171165982, lng: 78.038666512 },
        alt : "Image Taj Mahal",
    },   
    {
        id: 8,
        imagePath: "images/img_bresil_jesus.jpg",
        description : "Voir le Christ Rédempteur à Rio de Janeiro",
        done: false,
        link : "https://www.instinct-voyageur.fr/visiter-le-christ-redempteur/",
        coordinates : { lat: -22.9510, lng: -43.20645 },
        alt : "Image Christ Rédempteur",
    }, 
    {
        id: 9,
        imagePath: "images/img_chutes_zambie.jpg",
        description : "Voir les chutes Victoria en Zambie",
        done: false,
        link : "https://www.voyage-afriquedusud.fr/zimbabwe/chutes-victoria/",
        coordinates : { lat: -17.9328500, lng: 25.8306600 },
        alt : "Image Chutes Victoria",
    }, 
    {
        id: 10,
        imagePath: "images/img_chambord_cerf.jpg",
        description : "Voir les cerfs au château de Chambord",
        done: false,
        link : "https://www.chambord.org/fr/preparer-ma-visite/",
        coordinates : { lat: 47.616478, lng: 1.516968 },
        alt : "Image Château de Chambord",
    }, 
    {
        id: 11,
        imagePath: "images/img_cenote_mexique.jpg",
        description : "Visiter les cénotes au Mexique",
        done: false,
        link : "https://cenotes.net/fr/a-campeche/miguelcolorado/",
        coordinates : { lat: 18.812518830455506, lng: -90.64668889008051 },
        alt : "Image cénotes",
    },  
    {
        id: 12,
        imagePath: "images/img_machu_picchu.jpg",
        description : "Visiter le Machu Picchu au Pérou",
        done: false,
        link : "https://www.evaneos.fr/perou/?gclid=2845e1b5ac701459bdfc8957bd8c73c1&gclsrc=3p.ds&msclkid=2845e1b5ac701459bdfc8957bd8c73c1&utm_source=bing&utm_medium=cpc&utm_campaign=B_DES_AMEA-Perou_FR_fr_FR_D%3A93&utm_term=tourisme%20p%C3%A9rou&utm_content=Keywords_Perou_D%3A93_Broad",
        coordinates : { lat: -13.1583300, lng:  -72.5313900 },
        alt : "Image Machu Picchu",
    },
    {
        id: 13,
        imagePath: "images/img_vietnam.jpg",
        description : "Visiter la baie d'Halong au Vietnam",
        done: false,
        link : "https://aufilduvietnam.com/visiter-baie-halong-incontournables/",
        coordinates : { lat: 20.8999964, lng:  107.1999992 },
        alt : "Image Baie d'Halong",
    }, 
    {
        id: 14,
        imagePath: "images/img_grand_canyon.jpg",
        description : "Voir le Grand Canyon aux USA",
        done: false,
        link : "https://www.canyontours.com/?msclkid=631792f47ed91affc6a0fa16690308e6&utm_source=bing&utm_medium=cpc&utm_campaign=Grand%20Canyon%20Tours&utm_term=grandcanyon%20trips&utm_content=Grand%20Canyon%20Tours",
        coordinates : { lat: 36.056595, lng:  -112.125092 },
        alt : "Image Grand Canyon",
    },  
    {
        id: 15,
        imagePath: "images/img_pyramides.jpg",
        description : "Voir les pyramides de Gizeh en Egypte",
        done: false,
        link : "https://monsieurmadameexplore.com/visiter-les-pyramides-de-gizeh-la-merveille-des-merveilles",
        coordinates : { lat: 29.977296, lng:  31.132496 },
        alt : "Image Pyramides",
    }, 
    {
        id: 16,
        imagePath: "images/img_petra.jpg",
        description : "Visiter Pétra en Jordanie",
        done: false,
        link : "https://unsacsurledos.com/visiter-petra/",
        coordinates : { lat: 30.3207200, lng:  35.4839200 },
        alt : "Image Pétra",
    }, 
    {
        id: 17,
        imagePath: "images/img_lac_titicaca.jpg",
        description : "Voyager sur le lac Titicaca au Pérou",
        done: false,
        link : "https://www.voyageperou.info/lac-titicaca/",
        coordinates : { lat: -15.925400, lng:  -69.335400 },
        alt : "Image Lac Titicaca",
    }, 
    {
        id: 18,
        imagePath: "images/img_australie.jpg",
        description : "Voyager à Fitzroy Island en Australie",
        done: false,
        link : "https://www.oohmyworld.com/fitzroy-island-lile-nature-et-farniente-a-cairns-en-australie/",
        coordinates : { lat: -16.9333296, lng:  146.0 },
        alt : "Image Fitzroy Island",
    },
    {
        id: 19,
        imagePath: "images/img_mongolie.jpg",
        description : "Effectuer la grande traversée des steppes mongoles",
        done: false,
        link : "https://www.evaneos.fr/mongolie/itineraire/21807-la-grande-traversee-des-steppes-mongoles-en-petit-groupe/",
        coordinates : { lat: 43.66415426719836, lng:  101.51490771996444},
        alt : "Image Mongolie",
    }, 
    {
        id: 20,
        imagePath: "images/img_groeland.jpg",
        description : "Faire un voyage au Groenland",
        done: false,
        link : "https://generationvoyage.fr/voyager-groenland/",
        coordinates : { lat: 71.70237900000001, lng:  -42.17717450000001},
        alt : "Image Groenland",
    },
]

export { data };